[env]
_.path = [ '{{config_root}}/node_modules/.bin' ]

[settings]
experimental = true
lockfile = true

[tools]
hk = { version = "1.48.0", postinstall = 'if [ -z "$CI" ]; then hk install --mise; fi' }
node = { version = "lts", postinstall = "corepack enable" }
pkl = "latest"
