catalogMode: prefer
cleanupUnusedCatalogs: true
saveExact: true
shellEmulator: true
strictPeerDependencies: false

packages:
  - fixtures/*
  - src/*

overrides:
  semver@6: ^7.0.0

patchedDependencies:
  eslint-config-flat-gitignore: patches/eslint-config-flat-gitignore.patch

catalogs:
  dev:
    "@antfu/ni": 28.2.0
    "@eslint-react/shared": 2.13.0
    "@eslint/config-inspector": 1.4.2
    "@isentinel/tsconfig": 1.2.0
    "@stylistic/eslint-plugin-migrate": 4.4.1
    "@types/node": 22.16.0
    "@types/yargs": 17.0.35
    bumpp: 10.4.1
    eslint-typegen: 2.3.1
    jiti: 2.6.1
    lint-staged: 16.2.7
    parse-gitignore-ts: 1.0.0
    pnpm-workspace-yaml: 1.5.0
    publint: 0.3.17
    rimraf: 6.1.3
    simple-git-hooks: 2.13.1
    tsdown: 0.20.3
    tsx: 4.21.0
    type-fest: 5.4.4
    typescript: 5.9.3
    unplugin-unused: 0.5.7
  peer:
    "@vitest/eslint-plugin": 1.6.9
    eslint: 9.39.2
    eslint-plugin-erasable-syntax-only: 0.4.0
    eslint-plugin-eslint-plugin: 7.2.0
    eslint-plugin-jest: 29.15.0
    eslint-plugin-jest-extended: 3.0.1
    eslint-plugin-n: 17.24.0
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-react-naming-convention: 2.3.13
    eslint-plugin-react-x: 2.3.13
  prod:
    "@antfu/install-pkg": 1.1.0
    "@clack/prompts": 1.0.1
    "@cspell/eslint-plugin": 9.6.4
    "@eslint-community/eslint-plugin-eslint-comments": 4.6.0
    "@eslint/compat": 2.0.2
    "@eslint/markdown": 7.5.1
    "@isentinel/dict-rbxts": 1.0.1
    "@isentinel/dict-roblox": 1.0.3
    "@isentinel/eslint-plugin-comment-length": 2.2.0
    "@pobammer-ts/eslint-cease-nonsense-rules": 1.30.0
    "@stylistic/eslint-plugin": 5.9.0
    "@typescript-eslint/eslint-plugin": 8.56.0
    "@typescript-eslint/parser": 8.56.0
    ansis: 4.2.0
    eslint-config-flat-gitignore: 2.2.1
    eslint-config-prettier: 10.1.8
    eslint-flat-config-utils: 3.0.1
    eslint-merge-processors: 2.0.0
    eslint-plugin-antfu: 3.2.2
    eslint-plugin-arrow-return-style-x: 1.2.6
    eslint-plugin-better-max-params: 1.0.0
    eslint-plugin-de-morgan: 2.0.0
    eslint-plugin-flawless: 0.1.0
    eslint-plugin-format-lua: 1.0.1-beta.2
    eslint-plugin-import-lite: 0.3.0
    eslint-plugin-jsdoc: 62.7.0
    eslint-plugin-jsonc: 3.0.0
    eslint-plugin-oxfmt: 0.0.15
    eslint-plugin-package-json: 0.89.0
    eslint-plugin-perfectionist: 5.6.0
    eslint-plugin-pnpm: 1.5.0
    eslint-plugin-prettier: 5.5.5
    eslint-plugin-promise: 7.2.1
    eslint-plugin-roblox-ts: 1.4.0
    eslint-plugin-sentinel: 0.1.2
    eslint-plugin-sonarjs: 3.0.6
    eslint-plugin-toml: 1.1.1
    eslint-plugin-unicorn: 63.0.0
    eslint-plugin-unused-imports: 4.4.1
    eslint-plugin-yml: 3.2.1
    find-up-simple: 1.0.1
    globals: 17.3.0
    jsonc-eslint-parser: 3.1.0
    local-pkg: 1.1.2
    oxfmt: 0.34.0
    prettier: 3.8.1
    prettier-plugin-jsdoc: 1.8.0
    toml-eslint-parser: 1.0.3
    yaml-eslint-parser: 2.0.0
    yargs: 18.0.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
