packages:
  - fixtures/*

catalogs:
  dev:
    "@antfu/ni": 25.0.0
    "@eslint/config-inspector": 1.2.0
    "@isentinel/tsconfig": 1.0.0
    "@stylistic/eslint-plugin-migrate": 4.4.1
    "@types/fs-extra": 11.0.4
    "@types/node": 24.3.1
    "@types/prompts": 2.4.9
    "@types/yargs": 17.0.33
    bumpp: 10.2.3
    eslint-plugin-unused-imports: 4.2.0
    eslint-typegen: 2.3.0
    esno: 4.8.0
    execa: 9.6.0
    fast-glob: 3.3.3
    fs-extra: 11.3.1
    jiti: 2.5.1
    lint-staged: 16.1.6
    parse-gitignore-ts: 1.0.0
    pnpm-workspace-yaml: 1.1.1
    rimraf: 6.0.1
    simple-git-hooks: 2.13.1
    tsdown: 0.14.2
    type-fest: 4.41.0
    typescript: 5.9.2
  peer:
    "@eslint-react/eslint-plugin": 1.52.5
    "@vitest/eslint-plugin": 1.3.9
    eslint: 9.33.0
    eslint-plugin-eslint-plugin: 7.0.0
    eslint-plugin-jest: 29.0.1
    eslint-plugin-n: 17.21.3
    eslint-plugin-react-roblox-hooks: 5.1.0-rbx.1
  prod:
    "@antfu/install-pkg": 1.1.0
    "@clack/prompts": 0.11.0
    "@cspell/eslint-plugin": 9.2.1
    "@eslint/compat": 1.3.2
    "@eslint/markdown": 7.2.0
    "@eslint-community/eslint-plugin-eslint-comments": 4.5.0
    "@isentinel/dict-rbxts": 1.0.1
    "@isentinel/dict-roblox": 1.0.3
    "@isentinel/eslint-plugin-comment-length": 2.2.0
    "@prettier/plugin-oxc": 0.0.4
    "@shopify/eslint-plugin": 50.0.0
    "@stylistic/eslint-plugin": 6.0.0-beta.1
    "@typescript-eslint/eslint-plugin": 8.39.1
    "@typescript-eslint/parser": 8.39.1
    ansis: 4.1.0
    eslint-config-flat-gitignore: 2.1.0
    eslint-config-prettier: 10.1.8
    eslint-flat-config-utils: 2.1.1
    eslint-import-resolver-node: 0.3.9
    eslint-merge-processors: 2.0.0
    eslint-plugin-antfu: 3.1.1
    eslint-plugin-arrow-return-style-x: 1.2.6
    eslint-plugin-better-max-params: 1.0.0
    eslint-plugin-de-morgan: 1.3.1
    eslint-plugin-format-lua: 1.0.1-beta.2
    eslint-plugin-import-lite: 0.3.0
    eslint-plugin-jsdoc: 54.0.0
    eslint-plugin-jsonc: 2.20.1
    eslint-plugin-no-only-tests: 3.3.0
    eslint-plugin-package-json: 0.53.0
    eslint-plugin-perfectionist: 4.15.0
    eslint-plugin-pnpm: 1.1.1
    eslint-plugin-prettier: 5.5.4
    eslint-plugin-promise: 7.2.1
    eslint-plugin-roblox-ts: 1.1.0
    eslint-plugin-sentinel: 0.1.2
    eslint-plugin-sonarjs: 3.0.5
    eslint-plugin-toml: 0.12.0
    eslint-plugin-unicorn: 60.0.0
    eslint-plugin-yml: 1.18.0
    jsonc-eslint-parser: 2.4.0
    local-pkg: 1.1.2
    prettier: 3.6.2
    prettier-plugin-jsdoc: 1.3.3
    prompts: 2.4.2
    toml-eslint-parser: 0.10.0
    yaml-eslint-parser: 1.3.0
    yargs: 18.0.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
