catalogMode: strict

packages:
  - fixtures/*
  - src/*

patchedDependencies:
  eslint-config-flat-gitignore: patches/eslint-config-flat-gitignore.patch

catalogs:
  dev:
    "@antfu/ni": 27.0.1
    "@eslint/config-inspector": 1.3.0
    "@isentinel/tsconfig": 1.0.0
    "@stylistic/eslint-plugin-migrate": 4.4.1
    "@types/node": 22.16.0
    "@types/prompts": 2.4.9
    "@types/yargs": 17.0.35
    bumpp: 10.3.2
    eslint-typegen: 2.3.0
    jiti: 2.6.1
    lint-staged: 16.2.7
    parse-gitignore-ts: 1.0.0
    pnpm-workspace-yaml: 1.3.0
    rimraf: 6.1.2
    simple-git-hooks: 2.13.1
    tsdown: 0.16.4
    tsx: 4.21.0
    type-fest: 5.3.0
    typescript: 5.9.3
  peer:
    "@vitest/eslint-plugin": 1.5.1
    eslint: 9.39.1
    eslint-plugin-erasable-syntax-only: 0.4.0
    eslint-plugin-eslint-plugin: 7.2.0
    eslint-plugin-jest: 29.0.1
    eslint-plugin-n: 17.23.1
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-react-naming-convention: 2.3.12
    eslint-plugin-react-x: 2.3.12
  prod:
    "@antfu/install-pkg": 1.1.0
    "@clack/prompts": 0.11.0
    "@cspell/eslint-plugin": 9.4.0
    "@eslint-community/eslint-plugin-eslint-comments": 4.5.0
    "@eslint/compat": 2.0.0
    "@eslint/markdown": 7.5.1
    "@isentinel/dict-rbxts": 1.0.1
    "@isentinel/dict-roblox": 1.0.3
    "@isentinel/eslint-plugin-comment-length": 2.2.0
    "@prettier/plugin-oxc": 0.0.4
    "@shopify/eslint-plugin": 50.0.0
    "@stylistic/eslint-plugin": 5.5.0
    "@typescript-eslint/eslint-plugin": 8.46.4
    "@typescript-eslint/parser": 8.46.4
    ansis: 4.2.0
    eslint-config-flat-gitignore: 2.1.0
    eslint-config-prettier: 10.1.8
    eslint-flat-config-utils: 2.1.4
    eslint-import-resolver-node: 0.3.9
    eslint-merge-processors: 2.0.0
    eslint-plugin-antfu: 3.1.1
    eslint-plugin-arrow-return-style-x: 1.2.6
    eslint-plugin-better-max-params: 1.0.0
    eslint-plugin-de-morgan: 2.0.0
    eslint-plugin-flawless: 0.1.0
    eslint-plugin-format-lua: 1.0.1-beta.2
    eslint-plugin-import-lite: 0.3.0
    eslint-plugin-jsdoc: 61.1.12
    eslint-plugin-jsonc: 2.21.0
    eslint-plugin-no-only-tests: 3.3.0
    eslint-plugin-package-json: 0.85.0
    eslint-plugin-perfectionist: 4.15.1
    eslint-plugin-pnpm: 1.3.0
    eslint-plugin-prettier: 5.5.4
    eslint-plugin-promise: 7.2.1
    eslint-plugin-roblox-ts: 1.3.0
    eslint-plugin-sentinel: 0.1.2
    eslint-plugin-sonarjs: 3.0.5
    eslint-plugin-toml: 0.12.0
    eslint-plugin-unicorn: 62.0.0
    eslint-plugin-unused-imports: 4.3.0
    eslint-plugin-yml: 1.19.0
    find-up-simple: 1.0.1
    jsonc-eslint-parser: 2.4.1
    local-pkg: 1.1.2
    prettier: 3.6.2
    prettier-plugin-jsdoc: 1.5.0
    prompts: 2.4.2
    toml-eslint-parser: 0.10.0
    yaml-eslint-parser: 1.3.2
    yargs: 18.0.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
