/**
 * Generates a static list of oxlint's default-enabled rules by running
 * `oxlint --print-config` against a minimal config with only our plugins.
 *
 * This is a workaround for https://github.com/oxc-project/oxc/issues/19409
 * where `categories: "off"` also suppresses rules inside `overrides`.
 */
import { execSync } from "node:child_process";
import fs from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { URL } from "node:url";

// Same plugins used in src/oxlint.ts
const plugins = ["eslint", "unicorn", "typescript", "import", "jsdoc", "promise", "node", "oxc"];

const tempConfig = {
	$schema: "./node_modules/oxlint/configuration_schema.json",
	plugins,
	rules: {},
};

const tempDir = tmpdir();
const tempFile = path.join(tempDir, "oxlint-defaults-probe.json");
await fs.writeFile(tempFile, JSON.stringify(tempConfig));

let output: string;
try {
	output = execSync(`pnpm oxlint --print-config -c ${tempFile}`, {
		cwd: new URL("..", import.meta.url).pathname.replace(/^\/([A-Z]:)/, "$1"),
		encoding: "utf-8",
		stdio: ["pipe", "pipe", "pipe"],
	});
} finally {
	// oxlint-disable-next-line no-empty-function -- intentional noop
	await fs.unlink(tempFile).catch(() => {});
}

// Strip leading non-JSON lines (e.g. pnpm script banner)
const jsonStart = output.indexOf("{");
const parsed = JSON.parse(output.slice(jsonStart)) as {
	rules: Record<string, string>;
};

const defaults = Object.entries(parsed.rules)
	.filter(([, severity]) => severity !== "allow")
	.map(([name]) => name)
	.sort();

const content = `// Auto-generated by scripts/oxlint-defaults.ts — do not edit
export const oxlintDefaultRules: ReadonlySet<string> = new Set([
${defaults.map((r) => `\t"${r}",`).join("\n")}
]);
`;

await fs.writeFile(new URL("../src/oxlint-defaults.generated.ts", import.meta.url), content);

console.log(`Generated ${defaults.length} default oxlint rules.`);
