/**
 * Generates a static list of oxlint's default-enabled rules by running
 * `oxlint --print-config` against a minimal config with only our plugins.
 *
 * This is a workaround for https://github.com/oxc-project/oxc/issues/19409
 * where `categories: "off"` also suppresses rules inside `overrides`.
 */
import { execSync } from "node:child_process";
import fs from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { URL } from "node:url";

// Same plugins used in src/oxlint.ts
const plugins = [
	"eslint",
	"unicorn",
	"typescript",
	"import",
	"jsdoc",
	"jest",
	"vitest",
	"promise",
	"node",
	"oxc",
];

const temporaryConfig = {
	$schema: "./node_modules/oxlint/configuration_schema.json",
	plugins,
	rules: {},
};

const temporaryDirectory = tmpdir();
const temporaryFile = path.join(temporaryDirectory, "oxlint-defaults-probe.json");
await fs.writeFile(temporaryFile, JSON.stringify(temporaryConfig));

let output: string;
try {
	output = execSync(`pnpm dlx oxlint --print-config -c ${temporaryFile}`, {
		cwd: new URL("..", import.meta.url).pathname.replace(/^\/([A-Z]:)/, "$1"),
		encoding: "utf-8",
		stdio: ["pipe", "pipe", "pipe"],
	});
} finally {
	await fs.unlink(temporaryFile).catch(() => {
		/* noop */
	});
}

// Strip leading non-JSON lines (e.g. pnpm script banner)
const jsonStart = output.indexOf("{");
const parsed = JSON.parse(output.slice(jsonStart)) as {
	rules: Record<string, string>;
};

const defaults = Object.entries(parsed.rules)
	.filter(([, severity]) => severity !== "allow")
	.map(([name]) => name)
	.sort();

// Also parse ALL native oxlint rule names from --rules
const rulesOutput = execSync("pnpm dlx oxlint --rules", {
	cwd: new URL("..", import.meta.url).pathname.replace(/^\/([A-Z]:)/, "$1"),
	encoding: "utf-8",
	stdio: ["pipe", "pipe", "pipe"],
});

const allRules: Array<string> = [];
for (const line of rulesOutput.split("\n")) {
	const match = /^\|\s+([\w-]+)\s+\|\s+(\w+)/.exec(line);
	if (match) {
		const [, rule, source] = match;
		allRules.push(`${source}/${rule}`);
	}
}

allRules.sort();

const content = `/* oxlint-disable @cspell/spellchecker -- Autogenerated */
// Auto-generated by scripts/oxlint-defaults.ts — do not edit

export const oxlintDefaultRules: ReadonlySet<string> = new Set([
${defaults.map((rule) => `\t"${rule}",`).join("\n")}
]);

export type OxlintNativeRuleName =
${allRules.map((rule) => `\t| "${rule}"`).join("\n")};
`;

await fs.writeFile(new URL("../src/oxlint/oxlint.generated.ts", import.meta.url), content);

console.log(`Generated ${defaults.length} default rules, ${allRules.length} native rule names.`);
