import fs from "node:fs/promises";
import process from "node:process";

import { deriveRobloxAllowedWords } from "./roblox-allowed-words-shared.ts";

/**
 * Snapshot the Roblox names that `naming: { allowedWords: true }` hands to
 * `flawless/naming-convention` at build time.
 *
 * The names are scraped out of `@rbxts/types`, which ships ~4MB of `.d.ts`
 * across three files. Reading those on every config load - to answer a question
 * whose answer only changes when the package is bumped - would cost every
 * consumer far more than the snapshot does, and `@rbxts/types` is a
 * devDependency here, so a consumer may not have the same version installed (or
 * any). `roblox-allowed-words.spec.ts` fails when the snapshot drifts from the
 * installed package.
 *
 * `--check` reports drift instead of writing, for the same reason
 * `type-aware-gen.ts` has one: it has to run before anything that runs
 * `pnpm gen`, which repairs the file in place and hides the drift.
 */

const OUTPUT = new URL("../src/generated/roblox-allowed-words.ts", import.meta.url);

/**
 * Renders the snapshot, or reports the drift when checking.
 *
 * @returns The process exit code.
 */
async function main(): Promise<number> {
	const checking = process.argv.includes("--check");
	const words = await deriveRobloxAllowedWords();
	const desired = [
		"// Generated by scripts/roblox-allowed-words-gen.ts — do not edit.",
		`export const ROBLOX_ALLOWED_WORDS: ReadonlyArray<string> = ${JSON.stringify(words, null, 2)};`,
		"",
	].join("\n");

	// An unreadable (or absent) file can never equal `desired`, so it falls
	// through to the write or the drift report.
	const current = await fs.readFile(OUTPUT, "utf8").catch(() => "");
	if (current === desired) {
		if (!checking) {
			console.log(`[roblox-allowed-words] ${words.length} words.`);
		}

		return 0;
	}

	if (checking) {
		console.error(
			"[roblox-allowed-words] src/generated/roblox-allowed-words.ts is out of " +
				"sync with the installed @rbxts/types. Run `pnpm gen` and commit the result.",
		);
		return 1;
	}

	await fs.writeFile(OUTPUT, desired);
	return 0;
}

process.exit(await main());
