/**
 * Generates `src/oxlint/typegen-defaults.d.ts`: literal-typed maps of the
 * oxlint preset's effective default rule entries, consumed by the
 * redundant-override check (`redundancyCheck` option) of the oxlint factory.
 *
 * The oxlint factory is synchronous and returns a plain config whose rules all
 * live in ordered `overrides`, so extraction builds the config once per
 * formatter probe and merges the overrides matching each representative file
 * (last entry wins, whole-entry replacement). Everything else mirrors
 * `scripts/typegen-defaults.ts` via `scripts/typegen-defaults-shared.ts`.
 */
import type { OxlintConfig } from "oxlint";
import picomatch from "picomatch";

import { isentinel } from "../src/oxlint/index.ts";
import type { OxlintFactoryOptions } from "../src/oxlint/index.ts";
import type { ScopeRules } from "./typegen-defaults-shared.ts";
import {
	assertExtractionSane,
	combineProbes,
	deltaAgainst,
	FORMATTER_PROBES,
	logVariantCounts,
	VARIANT_KEYS,
	VARIANT_OPTIONS,
	writeDefaultsFile,
} from "./typegen-defaults-shared.ts";

type Variant = (typeof VARIANT_KEYS)[number];

type GeneratorOptions = Omit<OxlintFactoryOptions, "name">;

/**
 * The factory called through a plain signature: its redundancy-validation
 * generics cannot infer against wide (non-literal) options types, so this
 * wrapper pins the parameter to `OxlintFactoryOptions` (still fully checked)
 * and the return to the resolved `OxlintConfig`.
 *
 * @param options - Factory options for this extraction run.
 * @returns The generated oxlint config.
 */
function buildConfig(options: OxlintFactoryOptions): OxlintConfig {
	return isentinel(options);
}

/**
 * Deterministic base options: no environment detection and type-aware rules
 * pinned on so their defaults are covered.
 */
const BASE_OPTIONS = {
	name: "isentinel",
	gitignore: false,
	isAgent: false,
	isInEditor: false,
	options: { typeAware: true },
} satisfies OxlintFactoryOptions;

const FEATURE_OPTIONS: GeneratorOptions = {
	eslintPlugin: true,
	react: true,
	test: { jest: true, vitest: true },
};

const SCOPE_FILES = {
	main: "src/index.ts",
	react: "src/component.tsx",
	test: "src/component.test.ts",
} as const;
type ScopeFile = keyof typeof SCOPE_FILES;

interface VariantExtraction {
	main: ScopeRules;
	react: ScopeRules;
	sourceFeature: ScopeRules;
	test: ScopeRules;
}

/**
 * Merge the ordered overrides of one generated config for a representative
 * file. Later overrides replace earlier entries wholesale, matching oxlint's
 * behavior.
 *
 * @param config - The generated oxlint config.
 * @param file - Representative file path for the scope.
 * @returns The merged raw rule entries.
 */
function mergedRulesFromConfig(config: OxlintConfig, file: string): Record<string, unknown> {
	const merged: Record<string, unknown> = {};
	const overrides = config.overrides ?? [];

	for (const override of overrides) {
		if (override.rules === undefined) {
			continue;
		}

		if (!picomatch.isMatch(file, override.files, { dot: true })) {
			continue;
		}

		Object.assign(merged, override.rules);
	}

	return merged;
}

/**
 * Build the config once per formatter probe and combine the merged rules of
 * each scope file.
 *
 * @param options - Factory options for this extraction run.
 * @param scopes - Scope names to extract, resolved to representative files.
 * @returns Combined rules per scope.
 */
function extractScopes(
	options: GeneratorOptions,
	scopes: ReadonlyArray<ScopeFile>,
): Record<string, ScopeRules> {
	const [rulesA, rulesB] = FORMATTER_PROBES.map((formatters) => {
		const config = buildConfig({ ...BASE_OPTIONS, ...options, formatters });
		return scopes.map((scope) => mergedRulesFromConfig(config, SCOPE_FILES[scope]));
	});

	return Object.fromEntries(
		scopes.map((scope, index): [string, ScopeRules] => [
			scope,
			combineProbes(rulesA?.[index] ?? {}, rulesB?.[index] ?? {}),
		]),
	);
}

function extractVariant(variant: Variant): Record<string, ScopeRules> {
	const variantOptions = VARIANT_OPTIONS[variant];

	const baseScopes = extractScopes(variantOptions, ["main"]);
	const featureScopes = extractScopes({ ...variantOptions, ...FEATURE_OPTIONS }, [
		"main",
		"test",
		"react",
	]);

	const main = baseScopes["main"] ?? {};
	const sourceFeature = deltaAgainst(featureScopes["main"] ?? {}, [main]);

	return {
		main,
		react: deltaAgainst(featureScopes["react"] ?? {}, [sourceFeature, main]),
		sourceFeature,
		test: deltaAgainst(featureScopes["test"] ?? {}, [sourceFeature, main]),
	} satisfies VariantExtraction;
}

const extractions: Record<string, Record<string, ScopeRules>> = {};
for (const variant of VARIANT_KEYS) {
	const extraction = extractVariant(variant);
	extractions[variant] = extraction;
	assertExtractionSane(`oxlint ${variant}`, extraction, "main", "no-alert");
	logVariantCounts("oxlint ", variant, extraction);
}

const banner = `/* eslint-disable */
/* prettier-ignore */
// Generated by scripts/typegen-defaults-oxlint.ts — do not edit.
// Effective oxlint preset defaults per scope, keyed per variant
// ("<type>_<roblox|std>", or "*" when identical across variants).
// \`{ severityOnly }\` markers denote defaults whose real options are
// environment-dependent and were not captured.
`;

await writeDefaultsFile(
	banner,
	extractions,
	{
		main: "OxlintMainRuleDefaults",
		react: "OxlintReactRuleDefaults",
		sourceFeature: "OxlintSourceFeatureRuleDefaults",
		test: "OxlintTestRuleDefaults",
	},
	"src/oxlint/typegen-defaults.d.ts",
);
